pipeline {
    agent any

    environment {
        DOCKER_IMAGE = "eureka-server:latest"
    }

    stages {
        stage('Checkout Code') {
            steps {
                git branch: 'main',
                    url: 'https://github.com/shreyashsingrupkar/SpringBootMicoservices.git'
            }
        }

        stage('Build with Maven') {
            steps {
                dir('eureka-server') {
                    echo "Building Eureka Server..."
                    sh './mvnw clean package -DskipTests'
                }
            }
        }

        stage('Build Docker Image') {
            steps {
                dir('eureka-server') {
                    script {
                        echo "Building Docker Image..."
                        sh "docker build -t ${DOCKER_IMAGE} ."
                    }
                }
            }
        }

        stage('Verify Docker Image') {
            steps {
                sh "docker images | grep eureka-server"
            }
        }
    }

    post {
        success {
            echo "✅ Eureka Server build and Docker image created successfully!"
        }
        failure {
            echo "❌ Build failed! Please check the logs."
        }
    }
}
